import { describe, expect, it } from 'vitest'

import * as core from './index'

describe('core 公开导出', () => {
  it('运行时导出面完整（适配层依赖这些名字，删改需同步 react / vue / nuxt）', () => {
    expect(Object.keys(core).sort()).toEqual(
      [
        // types
        'BLUR_MASK_DEVIATION_FACTOR',
        'BLUR_MAX_MASK_SIZE',
        'BLADE_COUNT_DEFAULT',
        'MAX_BLADE_COUNT',
        'MAX_SLAT_WIDTH',
        'MAX_WAVE_WIDTH',
        'MIN_BLADE_COUNT',
        'MIN_SLAT_WIDTH',
        'MIN_WAVE_WIDTH',
        'QR_GRID_CELL_PX',
        'REVEAL_VAR',
        'SLAT_WIDTH_DEFAULT',
        'SWEEP_VAR',
        'WAVE_WIDTH_DEFAULT',
        'DIAMOND_COVERAGE_FACTOR',
        'DIAMOND_MASK_IMAGE',
        'HEXAGON_COVERAGE_FACTOR',
        'HEXAGON_MASK_IMAGE',
        'RECTANGLE_COVERAGE_MARGIN',
        'SOLID_RECT_MASK_IMAGE',
        'SQUARE_COVERAGE_MARGIN',
        'STAR_CIRCUMRADIUS_FACTOR',
        'STAR_INNER_RATIO',
        'STAR_MASK_IMAGE',
        'THEME_ANIMATION_DEFAULTS',
        'THEME_ANIMATION_STYLE_ID',
        'TRIANGLE_CIRCUMRADIUS_FACTOR',
        'TRIANGLE_MASK_IMAGE',
        'THEME_STORAGE_KEY',
        'ThemeAnimationDirection',
        'ThemeAnimationType',
        'resolveAnimationOptions',
        // masks
        'BLINDS_FEATHER_RATIO',
        'BLINDS_MAX_FEATHER_PX',
        'CIRCLE_MASK_IMAGE',
        'CIRCLE_SIZE_FACTOR',
        'CLOCK_SWEEP_TAIL_DEG',
        'FULL_CIRCLE_DEG',
        'RIPPLE_CREST_ALPHA',
        'RIPPLE_TRAIL_COUNT',
        'SCAN_BAND_ALPHA',
        'SCAN_BAND_WIDTH_PX',
        'SCAN_FADE_WIDTH_PX',
        'getBlurCircleMaskGeometry',
        'getBlurCircleMaskImage',
        'getBlindsFeatherPx',
        'getCircleMaskGeometry',
        'getCircleRevertHoleGeometry',
        'getCircleRevertMaskGeometry',
        'getClockSweepRevealSpec',
        'getDiamondMaskGeometry',
        'getHexagonMaskGeometry',
        'getFanBladeStepDeg',
        'getFanRevealSpec',
        'getMaskGeometry',
        'getMaxRadiusToCorners',
        'getQrGridMaskSpec',
        'getRectangleMaskGeometry',
        'getRevealMaskSpec',
        'getRippleFrontExtentPx',
        'getRippleRevealSpec',
        'getSquareMaskGeometry',
        'getStarMaskGeometry',
        'getSweepMaskSpec',
        'getTriggerCenter',
        'getTriangleMaskGeometry',
        'isBlurAnimationType',
        'isRippleAnimationType',
        'isQrGridAnimationType',
        'isRevealAnimationType',
        'isShapeAnimationType',
        'isSweepAnimationType',
        // styles
        'DURATION_VAR',
        'EASING_VAR',
        'HOLE_RADIUS_VAR',
        'buildAnimationCSS',
        'getAnimationName',
        'injectAnimationStyle',
        'removeAnimationStyle',
        // orchestrate
        'SKIP_TRANSITION',
        'getViewportSize',
        'prefersReducedMotion',
        'runThemeTransition',
        'shouldSkipTransition',
        'supportsViewTransition',
        // uncontrolled
        'applyThemeClass',
        'hasThemeClass',
        'observeThemeClass',
        'readStoredTheme',
        'syncThemeOnMount',
        'writeStoredTheme',
        // controlled-sync
        'THEME_SYNC_TIMEOUT_MS',
        'waitForThemeSync',
      ].sort(),
    )
  })

  it('ThemeAnimationType 与常量与需求一致', () => {
    expect(core.ThemeAnimationType.CIRCLE).toBe('circle')
    expect(core.THEME_STORAGE_KEY).toBe('theme-switch-animation')
  })
})
